## Helper script for http_header_test.
# Performs a single CMLIB_FILE_DOWNLOAD call.
# If TEST_HTTP_HEADER_VALUE is defined, sets CMLIB_FILE_DOWNLOAD_HTTP_HEADER.
#
IF(NOT DEFINED CMAKE_SCRIPT_MODE_FILE)
    CMAKE_MINIMUM_REQUIRED(VERSION 3.18)
    PROJECT(CMLIB_HTTP_HEADER_DOWNLOAD_HELPER)
ENDIF()

LIST(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../../../")
FIND_PACKAGE(CMLIB)
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../../transform_git_uri.cmake")

IF(DEFINED TEST_HTTP_HEADER_VALUE)
    SET(CMLIB_FILE_DOWNLOAD_HTTP_HEADER "${TEST_HTTP_HEADER_VALUE}" CACHE STRING "" FORCE)
ENDIF()

TRANSFORM_GIT_URI_TO_HTTPS(
    URI "${CMLIB_REQUIRED_ENV_REMOTE_URL}/cmakelib-test/archive/v1.0.0.zip"
    OUTPUT_VAR VALID_HTTP_URI
)

SET(output_path "${CMLIB_REQUIRED_ENV_TMP_PATH}/http_header_test_file.txt")

CMLIB_FILE_DOWNLOAD(
    URI "${VALID_HTTP_URI}"
    STATUS_VAR status
    OUTPUT_PATH "${output_path}"
)
IF(NOT status)
    MESSAGE(FATAL_ERROR "Download failed")
ENDIF()

FILE(REMOVE "${output_path}")
FILE(REMOVE_RECURSE "${CMLIB_REQUIRED_ENV_TMP_PATH}")

