
IF(NOT DEFINED CMAKE_SCRIPT_MODE_FILE)
	CMAKE_MINIMUM_REQUIRED(VERSION 3.18)
	PROJECT(CMLIB_CACHE_TEST)
ENDIF()

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/test_resources.cmake")

TEST_RESOURCES_DOWNLOAD_ENABLE()
TEST_RESOURCES_DOWNLOAD()
TEST_RESOURCES_DOWNLOAD_DISABLE()