name: Linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

  workflow_dispatch:
  
jobs:   
  test_debian_buster:
    runs-on: ubuntu-latest
    container:
        image: cmakelib/build-linux:latest-debian-buster
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/

  test_ubuntu_1804:
    runs-on: ubuntu-latest
    container:
        image: cmakelib/build-linux:latest-ubuntu-1804
    steps:
      - uses: actions/checkout@v2
      - name: Git init
        run: git init
      - name: Add origin
        env:
          REPO_URL_TEST: ${{ github.repositoryUrl }}
        run: git remote add origin "$REPO_URL_TEST"
      - name: Run Tests
        run: cmake test/
          
  test_ubuntu_2004:
    runs-on: ubuntu-latest
    container:
        image: cmakelib/build-linux:latest-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
        
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
  
  test_macosx:
    runs-on: macosx-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
