name: Linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

  workflow_dispatch:
  
jobs:   
  test_debian_buster:
    runs-on: ubuntu-latest
    container:
        image: cmakelib/build-linux:latest-debian-buster
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
          
  test_ubuntu_2004:
    runs-on: ubuntu-latest
    container:
        image: cmakelib/build-linux:latest-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
