name: Mac OS tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

  workflow_dispatch:
  
jobs:   
  test_macos_11:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
  
