name: Windows tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

  workflow_dispatch:
  
jobs: 
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cmake test/
